---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "{{ eks_clustername }}"
  name: "{{ eks_clustername }}-nodejs-ingress"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "{{ eks_sslarn }}"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    external-dns.alpha.kubernetes.io/hostname: "{{ eks_microservice_url }}"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: "{{ eks_clustername }}-nodejs"
              port:
                number: 80

