---
apiVersion: v1
kind: Service
metadata:
  name: "{{ eks_clustername }}-nodejs"
  namespace: "{{ eks_clustername }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ eks_clustername }}-nodejs"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
