#############################################################
## NOT FOR PRODUCTION USE.                                 ##
## THE CONTENT OF THIS FILE IS FOR LEARNING PURPOSES ONLY  ##
## created by David Surey, Amazon Web Services, 2020       ##
#############################################################

- name: Create EC2 KeyPair 
  ec2_key:
    profile: "{{ aws_profile }}"
    name: "{{ eks_clustername }}-keypair"
    region: "{{ region }}"
  register: ec2_key_result
  
- name: Save Private Key for Bastion Access
  copy: content="{{ ec2_key_result.key.private_key }}" dest="{{ playbook_dir }}/keys/{{ eks_clustername }}_id_rsa_eks" mode=0600
  when: ec2_key_result.changed

- name: create bastion Environment
  cloudformation:
    profile: "{{ aws_profile }}"
    stack_name: "{{ eks_clustername }}-bastion"
    state: "present"
    region: "{{ region }}"
    disable_rollback: false
    template_parameters:
      EKSBastionInstanceType: "{{ bastion_instancetype }}"
      EKSBastionKeyPairName: "{{ eks_clustername }}-keypair"
    template: "{{ playbook_dir }}/templates/eks-bastion.template.yaml"
  register: bastion_informations

- name: save outputs to local file for ref 
  copy: 
    content: "{{ bastion_informations.stack_outputs | to_nice_yaml }}" 
    dest: "{{ playbook_dir }}/vars/dynamic/{{ eks_clustername }}_eks_bastion_ip.yaml"
